config/routes.rb
Rails.application.routes.draw do
  namespace :backoffice do
  get 'users/index'
  end

  namespace :backoffice do
  get 'ads/index'
  end

  post '/rate' => 'rater#create', :as => 'rate'
  
  get 'backoffice', to: 'backoffice/dashboard#index'
  
  namespace :backoffice do
    resources :send_mail, only: [:edit, :create]
    resources :categories, except: :show
    resources :ads, except: :show
    resources :admins, except: :show
    resources :users, except: [:show, :new, :create]
    resources :diagrams, only: :index
    get 'dashboard', to: 'dashboard#index'
  end

  namespace :site do
    get 'home', to: 'home#index'
    get 'search', to: 'search#ads'
    
    namespace :profile do
      resources :ads, except: :destroy
      resources :dashboard, only: :index
      resources :my_data, only: [:edit, :update]
    end
    
    resources :ad_detail, only: [:index, :show]
    resources :categories, only: [:show]
    resources :comments, only: [:show, :create, :destroy]
  end
  
  devise_for :admins, skip: :registrations
  
  devise_for :users, controllers: { 
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  
  root 'site/home#index'

end

app/controllers/backoffice/admins_controller.rb
class Backoffice::AdminsController < BackofficeController
  before_action :set_admin, only: [:edit, :update, :destroy]
  after_action :verify_authorized, only: [:new, :destroy]
  after_action :verify_policy_scoped, only: :index

  def index
    # @admins = Admin.all.order(:name)
    # @admins = Admin.with_restricted_access
    @admins = policy_scope(Admin).order(:name)
  end
  
  def new
    @admin = Admin.new
    authorize @admin
  end
  
  def create
    @admin = Admin.new(params_admin)
    if @admin.save
      redirect_to backoffice_admins_path, notice: "Administrador #{@admin.email} criada!"
    else
      render :new
    end
  end
  
  def edit
  end
  
  def update
    if @admin.update(params_admin)
      AdminMailer.update_email(current_admin, @admin).deliver_now
      redirect_to backoffice_admins_path, notice: "Administrador #{@admin.email} alterada!"
    else
      render :edit
    end
  end
  
  def destroy
    authorize @admin
    admin_email = @admin.email
    
    if @admin.destroy
      redirect_to backoffice_admins_path, notice: "Administrador #{admin_email} excluído!"
    else
      render :index
    end
  end
  
  private
  
  def set_admin
    @admin = Admin.find(params[:id])
  end
  
  def params_admin
    params[:admin].except!(:password, :password_confirmation) if password_blank?
    
    if @admin.blank?
      params.require(:admin).permit([:name, :role, :email, :password, :password_confirmation])
    else
      params.require(:admin).permit(policy(@admin).permitted_attributes)
    end
  end
  
  def password_blank?
    params[:admin][:password].blank? &&
    params[:admin][:password_confirmation].blank?
  end
end

app/controllers/backoffice/ads_controller.rb
class Backoffice::AdsController < BackofficeController
  before_action :set_ad, only: [:destroy, :edit, :update]
  
  def index
    @ads = Ad.order(created_at: :desc).page(params[:page]).per(10)
  end
  
  def new
    @ad = Ad.new
  end
  
  def create
    @ad = Ad.new(params_ad)
    @ad.admin = current_admin
    
    if @ad.save
      redirect_to backoffice_ads_path, notice: 'Anúncio criado!'
    else
      render :new
    end
  end
  
  def edit
  end
  
  def update
    if @ad.update(params_ad)
      redirect_to backoffice_ads_path, notice: 'Anúncio atualizado!'
    else
      render :edit
    end
  end
  
  def destroy
    if @ad.destroy
      redirect_to backoffice_ads_path, notice: 'Anúncio excluído!'
    else
      render :index
    end
  end
  
  private
  
  def set_ad
    @ad = Ad.friendly.find(params[:id])
  end
  
  def params_ad
    params.require(:ad).permit( :id, :title, :picture, :finish_date, 
      :category_id, :admin_id, :price, :description, :slug )
  end
end

app/controllers/backoffice/categories_controller.rb
class Backoffice::CategoriesController < BackofficeController
  before_action :set_category, only: [:destroy, :edit, :update]

  def index
    @categories = Category.all.order(:description)
  end
  
  def new
    @category = Category.new
  end
  
  def create
    @category = CategoryService.create(params_category)
    
    unless @category.errors.any?
      redirect_to backoffice_categories_path, notice: "Categoria #{@category.description} criada!"
    else
      render :new
    end
  end
  
  def edit
  end
  
  def update
    if @category.update(params_category)
      redirect_to backoffice_categories_path, notice: "Categoria #{@category.description} alterada!"
    else
      render :edit
    end
  end
  
  def destroy
    if @category.destroy
      redirect_to backoffice_categories_path, notice: 'Categoria excluída!'
    else
      render :index
    end
  end
  
  private
  
  def set_category
    @category = Category.friendly.find(params[:id])
  end
  
  def params_category
    params.require(:category).permit(:description)
  end
end

app/controllers/backoffice/categories_controller/category_service.rb
class Backoffice::CategoriesController::CategoryService
  attr_accessor :category
  
  def self.create(params_category)
    @category = Category.new(params_category)
    
    if @category.valid?
      @category.save!
    end
    
    @category
  end
end

app/controllers/backoffice/dashboard_controller.rb
class Backoffice::DashboardController < BackofficeController
  def index
  end
end

app/controllers/backoffice/diagrams_controller.rb
class Backoffice::DiagramsController < BackofficeController
  def index
    %x(bundle exec erd --filename='public/diagram')
  end
end

app/controllers/backoffice/send_mail_controller.rb
class Backoffice::SendMailController < ApplicationController
  def edit
    @admin = Admin.find(params[:id])
    
    respond_to do |format|
      format.js
    end
  end
  
  def create
    begin
      AdminMailer.send_message(current_admin, params[:'recipient-text'], params[:'subject-text'], params[:'message-text']).deliver_now
      @notify_message = 'E-mail enviado!'
      @notify_flag = 'success'
    rescue
      @notify_message = 'Erro ao enviar e-mail. Tente novamente...'
      @notify_flag = 'error'
    end
    
    respond_to do |format|
      format.js
    end
  end
end

app/controllers/backoffice/users_controller.rb
class Backoffice::UsersController < BackofficeController
  before_action :set_user, only: [:edit, :update, :destroy]

  def index
    @users = User.order(:email).page(params[:page]).per(10)
  end
  
  def edit
  end
  
  def update
    if @user.update(params_user)
      redirect_to backoffice_users_index_path, notice: "Usuário #{@user.email} alterado!"
    else
      render :edit
    end
  end
  
  def destroy
    if @user.destroy
      redirect_to backoffice_users_index_path, notice: "Usuário #{@user.email} excluído!"
    else
      render :index
    end
  end
  
  private
  
  def set_user
    @user = User.find(params[:id])
  end
  
  def params_user
    params[:user].except!(:password, :password_confirmation) if password_blank?
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
  
  def password_blank?
    params[:user][:password].blank? &&
    params[:user][:password_confirmation].blank?
  end
end

app/controllers/backoffice_controller.rb
class BackofficeController < ApplicationController
  before_action :authenticate_admin!
  layout 'backoffice'
  
  def pundit_user
    current_admin # current_user to Pundit
  end
end

app/helpers/backoffice/admins_helper.rb
module Backoffice::AdminsHelper
  OptionsForRoles = Struct.new(:id, :description)
  
  def options_for_roles
    Admin.roles_i18n.map do |key, value|
      OptionsForRoles.new(key, value)
    end
  end
end

app/helpers/backoffice/ads_helper.rb
module Backoffice::AdsHelper
end

app/helpers/backoffice/categories_helper.rb
module Backoffice::CategoriesHelper
end

app/helpers/backoffice/dashboard_helper.rb
module Backoffice::DashboardHelper
end

app/helpers/backoffice/diagrams_helper.rb
module Backoffice::DiagramsHelper
end

app/helpers/backoffice/send_mail_helper.rb
module Backoffice::SendMailHelper
end

app/helpers/backoffice/users_helper.rb
module Backoffice::UsersHelper
end

app/helpers/backoffice_helper.rb
module BackofficeHelper
end

app/views/backoffice/admins/edit.html.erb
<%= render partial: 'backoffice/admins/shared/form',
           locals: { action: 'Editando' } %>

app/views/backoffice/admins/index.html.erb
<h1 class="page-header">Administradores</h1>

<div>
  <div class="panel panel-default">
    <div class="panel-heading">
      Administradores do Sistema...
    </div>
    
    <div class="panel-body">
      <div class="table-responsive">
        <table class="table table-striped table-bordered table-hover">
          <thead>
            <tr>
              <th>#</th>
              <th>Nome</th>
              <th>E-mail</th>
              <th>Acesso</th>
              <th style="text-align: right">
                <% if policy(@admins).new? %>
                  <%= link_to new_backoffice_admin_path, class: 'btn btn-success btn-circle' do %>
                    <i class="fa fa-plus"></i>
                  <% end %>
                <% end %>
              </th>
            </tr>
          </thead>
          
          <tbody>
            <% @admins.each do |admin| %>
              <tr>
                <td><%= admin.id %></td>
                <td><%= admin.name %></td>
                <td><%= admin.email %></td>
                <td><%= admin.role_i18n %></td>
                <td style="text-align: right">
                  <% if current_admin.id != admin.id %>
                    <%= link_to edit_backoffice_send_mail_path(admin), remote: true, class: 'btn btn-info btn-circle' do %>
                      <i class="fa fa-envelope"></i>
                    <% end %>
                  <% end %>
                  
                  <%= link_to edit_backoffice_admin_path(admin), class: 'btn btn-primary btn-circle' do %>
                    <i class="fa fa-edit"></i>
                  <% end %>
                  
                  <% if current_admin.id != admin.id && policy(@admins).destroy? %>
                    <%= link_to backoffice_admin_path(admin), method: :delete, data: { confirm: t('messages.confirm_with', item: admin.name ) }, class: 'btn btn-danger btn-circle' do %>
                      <i class="fa fa-trash"></i>
                    <% end %>
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

<!-- Modal -->
<%= render partial: 'backoffice/admins/shared/modal_send_mail' %>

app/views/backoffice/admins/new.html.erb
<%= render partial: 'backoffice/admins/shared/form',
           locals: { action: 'Novo' } %>