config/routes.rb
Rails.application.routes.draw do
  namespace :backoffice do
  get 'users/index'
  end

  namespace :backoffice do
  get 'ads/index'
  end

  post '/rate' => 'rater#create', :as => 'rate'
  
  get 'backoffice', to: 'backoffice/dashboard#index'
  
  namespace :backoffice do
    resources :send_mail, only: [:edit, :create]
    resources :categories, except: :show
    resources :ads, except: :show
    resources :admins, except: :show
    resources :users, except: [:show, :new, :create]
    resources :diagrams, only: :index
    get 'dashboard', to: 'dashboard#index'
  end

  namespace :site do
    get 'home', to: 'home#index'
    get 'search', to: 'search#ads'
    
    namespace :profile do
      resources :ads, except: :destroy
      resources :dashboard, only: :index
      resources :my_data, only: [:edit, :update]
    end
    
    resources :ad_detail, only: [:index, :show]
    resources :categories, only: [:show]
    resources :comments, only: [:show, :create, :destroy]
  end
  
  devise_for :admins, skip: :registrations
  
  devise_for :users, controllers: { 
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  
  root 'site/home#index'

end

app/models/ad.rb
class Ad < ActiveRecord::Base
  # Constants
  QTT_PER_PAGE = 6

  # Associations
  belongs_to :user
  belongs_to :admin
  belongs_to :category, counter_cache: true
  has_many :comments, dependent: :delete_all
  
  # Validations
  validates :title, :description, :category, :price, presence: true
  validates :picture, :finish_date, presence: true
  validates :price, numericality: { greater_than: 0 }
  
  ## Gems
  # paperclip
  has_attached_file :picture, 
    styles: { large: '800x300#', medium: '320x150#', thumb: '100x100#' }, 
    default_url: '/images/:style/missing.png'
  validates_attachment_content_type :picture, content_type: /\Aimage\/.*\z/
  
  # money-rails
  monetize :price_cents
  
  # ratyrate
  ratyrate_rateable 'quality'
  
  # friendly_id
  include FriendlyId
  friendly_id :title, use: :slugged
  
  #Scopes
  scope :descending_order, ->(page) { 
    order(created_at: :desc).page(page).per(QTT_PER_PAGE) 
  }
  
  scope :search, ->(term, page) { 
    where("lower(title) LIKE ?", "%#{term.downcase}%").page(page).per(QTT_PER_PAGE)
  }
  
  scope :by_category, ->(id, page) { 
    where(category: id).page(page).per(QTT_PER_PAGE).order(created_at: :desc)
  }
  
  scope :to_the, ->(user) { where(user: user) }
  
  scope :random, ->(quantity) { limit(quantity).order("RANDOM()") }
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Associations
  has_many :ads, dependent: :delete_all
  
  # Enums
  enum role: {full_access: 0, restricted_access: 1}
  
  # Scopes
  scope :with_full_access, -> { where(role: 0) }
  scope :with_restricted_access, -> { where(role: 1) }
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/category.rb
class Category < ActiveRecord::Base
  # gem friendly_id
  include FriendlyId
  friendly_id :description, use: :slugged
  
  # Validations
  has_many :ads, dependent: :delete_all
  validates_presence_of :description
  
  # Scopes
  scope :order_by_description, -> { order(:description) }
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :ad
  
  validates :body, length: { minimum: 3 }
end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/profile_user.rb
class ProfileUser < ActiveRecord::Base
  belongs_to :user
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/user.rb
class User < ActiveRecord::Base
  # gem ratyrate
  ratyrate_rater
  
  #Associations
  has_many :ads, dependent: :delete_all
  has_many :comments, dependent: :delete_all
  has_one :profile_user
  accepts_nested_attributes_for :profile_user
  
  # Validations
  validate :nested_attributes
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  def nested_attributes
    if nested_attributes_blank?
      errors.add(:base, 'É necessário preencher o nome e o sobrenome.')
    end
  end
  
  def nested_attributes_blank?
    profile_user.first_name.blank? || profile_user.second_name.blank?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # gem devise
  before_filter :store_current_location, unless: :devise_controller?
  skip_before_action :verify_authenticity_token
  
  # gem pundit
  include Pundit
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  
  # Prevent CSRF attacks by raising an exception.
  protect_from_forgery with: :exception
  
  layout :layout_by_resoure
  
  private
  
  def layout_by_resoure
    if devise_controller? && resource_name == :admin
      'backoffice_devise'
    elsif devise_controller? && resource_name == :user
      'site_devise'
    else
      'application'
    end
  end
  
  def user_not_authorized
    flash[:alert] = 'Você não está autorizado para executar essa ação.'
    redirect_to(request.referrer || root_path)
  end
  
  def store_current_location
    store_location_for(:user, request.url)
  end
end

app/controllers/backoffice_controller.rb
class BackofficeController < ApplicationController
  before_action :authenticate_admin!
  layout 'backoffice'
  
  def pundit_user
    current_admin # current_user to Pundit
  end
end

app/controllers/rater_controller.rb
class RaterController < ApplicationController

  def create
    if user_signed_in?
      obj = params[:klass].classify.constantize.find(params[:id])
      obj.rate params[:score].to_f, current_user, params[:dimension]

      render :json => true
    else
      render :json => false
    end
  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  layout 'site'
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/backoffice/ads_helper.rb
module Backoffice::AdsHelper
end

app/helpers/backoffice_helper.rb
module BackofficeHelper
end

app/helpers/site/comments_helper.rb
module Site::CommentsHelper
end

app/helpers/site/home_helper.rb
module Site::HomeHelper
end

app/helpers/site/search_helper.rb
module Site::SearchHelper
end

app/views/backoffice/admins/shared/_form.html.erb
<h1 class="page-header">Administradores</h1>

<% if @admin.errors.any? %>
  <div class="alert alert-danger alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
    
    <ul>
      <% @admin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="panel panel-default">
  <div class="panel-heading">
    <%= action %> Administrador
  </div>
  
  <div class="panel-body">
    <div class="col-lg-6">
      <div class="table-responsive">
        <%= form_for([:backoffice, @admin]) do |f| %>
          <div class="form-group">
            <%= f.label 'Nome do administrador' %>
            <%= f.text_field :name, class: 'form-control', placeholder: 'Nome...' %>
          </div>
          
          <div class="form-group">
            <%= f.label :email %>
            <%= f.text_field :email, class: 'form-control', placeholder: 'E-mail...' %>
          </div>
          
          <% if policy(@admin).edit? %>
            <div class="form-group">
              <%= f.label :role %>
              <%= f.collection_radio_buttons(:role, options_for_roles, :id, :description) do |b| %>
                <div class="radio">
                  <%= b.label { b.radio_button + b.text } %>
                </div>
              <% end %>
            </div>
          <% end %>
          
          <div class="form-group">
            <%= f.label :password %>
            <%= f.password_field :password, class: 'form-control', placeholder: 'Senha...' %>
          </div>
          
          <div class="form-group">
            <%= f.label :password_confirmation %>
            <%= f.password_field :password_confirmation, class: 'form-control', placeholder: 'Confirmação de senha...' %>
          </div>
          
          <button type="submit" class="btn btn-default">Salvar</button>
        <% end %>
      </div>
    </div>
  </div>
  
</div>

app/views/backoffice/admins/shared/_modal_send_mail.html.erb
<div class="modal fade" id="sendMailModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="exampleModalLabel"><%= t('labels.new_message') %></h4>
      </div>
      
      <div class="modal-body">
        <%= form_tag(backoffice_send_mail_index_path, remote: true)  do %>
          <div class="form-group">
            <label for="recipient-text" class="control-label"><%= t('labels.recipient') %></label>
            <%= text_field_tag(:'recipient-text', nil, class: 'form-control', readonly: 'readonly' ) %>
          </div>
          
          <div class="form-group">
            <label for="recipient-text" class="control-label"><%= t('labels.subject') %></label>
            <%= text_field_tag(:'subject-text', nil, class: 'form-control', required: 'required' ) %>
          </div>
          
          <div class="form-group">
            <label for="message-text" class="control-label"><%= t('labels.message') %></label>
            <%= text_area_tag(:'message-text', nil, class: 'form-control' ) %>
          </div>
          
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal"><%= t('buttons.close') %></button>
            <%= submit_tag t('buttons.send_message'), class: 'btn btn-primary' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/shared/_notifications.html.erb
  <% if notice %>
    <%= javascript_tag "$.notify('#{notice}', 'success')" %>
  <% end %>
  
  <% if alert %>
    <%= javascript_tag "$.notify('#{alert}', 'error')" %>
  <% end %>